### PR TITLE
add wrapper for frequency jump in rf cavity

### PR DESCRIPTION
**Pull request by kryv**
Add wrapper for frequency jump in rf cavity.
I have cross checked with latest TLM.
I think we can change only for src/rfcavity.cpp, 
because of the unittest  does not check the frequency jump for now.

### CODE REVIEW

**Comment by mdavidsaver** [comment]
> because of the unittest does not check the frequency jump for now.

Would it be useful to add a test?  I think this would be as simple as copying one of the existing cavity test cases and adding ```reconfigure(elemidx, {'f':80.5*2})```, then correcting the expected output.

**Comment by shengb** [comment]
I would prefer to add a test case.

**Comment by kryv** [comment]
I have committed about  "clean up multip definition and add test for cavity frequency jump".

**Comment by mdavidsaver** [comment]
Code-wise this looks fine to me.

**Pull request merged**
